name: Terraform Validate

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
    
    - name: Terraform Format Check
      run: terraform fmt -check -recursive
    
    - name: Terraform Init
      working-directory: ./infrastructure
      run: terraform init -backend=false
    
    - name: Terraform Validate
      working-directory: ./infrastructure
      run: terraform validate
    
    - name: Terraform Plan
      working-directory: ./infrastructure
      run: terraform plan -out=plan.out
      env:
        TF_VAR_aws_region: "ap-southeast-2"
        TF_VAR_project_name: "eks-portfolio"
        TF_VAR_environment: "dev"
        TF_VAR_owner: "ci-validation"

  app-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: applications/frontend/package-lock.json
    
    - name: Install dependencies
      working-directory: ./applications/frontend
      run: npm ci
    
    - name: Run tests
      working-directory: ./applications/frontend
      run: npm test -- --coverage --watchAll=false